// ═══════════════════════════════════════════════════
// MOCK DATA (fallback)
// ═══════════════════════════════════════════════════
import { C } from "../constants/theme.js";

export const mkData = () => ({
  transactions: [
    { id:1, descricao:'Botijão de gás', data:'2026-03-23T12:00', conta:'Caixa', categoria:'Insumos', tipo:'despesa', valor:140.00 },
    { id:2, descricao:'Compra de pacote IA para programação', data:'2026-03-20T12:00', conta:'PIX', categoria:'Marketing', tipo:'despesa', valor:96.99 },
    { id:3, descricao:'Venda Pedido #3 - Selva / Jovanka', data:'2026-03-09T01:53', conta:'Caixa', categoria:'Vendas Delivery', tipo:'receita', valor:54.00 },
    { id:4, descricao:'Compra hostgator (domínio, email, hospedagem)', data:'2026-03-04T12:00', conta:'PIX', categoria:'Marketing', tipo:'despesa', valor:128.07 },
    { id:5, descricao:'Pagamento MEI - Fevereiro', data:'2026-03-03T22:31', conta:'PIX', categoria:'Impostos e Taxas', tipo:'despesa', valor:87.05 },
    { id:6, descricao:'Venda Pedido #2 - Pão Trançado', data:'2026-03-02T10:00', conta:'PIX', categoria:'Vendas Retirada', tipo:'receita', valor:32.00 },
    { id:7, descricao:'Venda Pedido #1 - Bambuguette', data:'2026-03-01T09:00', conta:'PIX', categoria:'Vendas Delivery', tipo:'receita', valor:50.00 },
    { id:8, descricao:'Farinha Especial T65 - 15kg', data:'2026-02-28T14:00', conta:'PIX', categoria:'Insumos', tipo:'despesa', valor:85.00 },
    { id:9, descricao:'Venda - Bambuguette Sem Glúten', data:'2026-02-25T08:00', conta:'PIX', categoria:'Vendas Delivery', tipo:'receita', valor:18.00 },
    { id:10, descricao:'Embalagens (caixas, sacolas)', data:'2026-02-20T10:00', conta:'Caixa', categoria:'Insumos', tipo:'despesa', valor:45.00 },
    { id:11, descricao:'Ovos Caipira (30 unid)', data:'2026-02-18T09:00', conta:'Caixa', categoria:'Insumos', tipo:'despesa', valor:36.00 },
    { id:12, descricao:'Venda - Pão Trançado + Bambuguette', data:'2026-02-15T08:30', conta:'PIX', categoria:'Vendas Delivery', tipo:'receita', valor:50.00 },
  ],
  produtos: [
    { id:1, nome:'Bambuguette', categoria:'panificação', quantidade:5, valor_unitario:18.00, prazo_validade:'2026-03-16', alerta_minimo:3, emoji:'🥖', descricao:'Pão artesanal de fermentação natural e longa' },
    { id:2, nome:'Bambuguette Sem Glúten', categoria:'panificação', quantidade:3, valor_unitario:18.00, prazo_validade:'2026-03-16', alerta_minimo:2, emoji:'🍞', descricao:'Polvilho de mandioca, fermento, ovos caipira' },
    { id:3, nome:'Pão Trançado', categoria:'panificação', quantidade:2, valor_unitario:32.00, prazo_validade:'2026-03-16', alerta_minimo:2, emoji:'🥐', descricao:'Farinha especial, ovos caipira, fermentação 24h' },
    { id:4, nome:'Pizza Margherita', categoria:'pizzas', quantidade:0, valor_unitario:55.00, prazo_validade:'2026-03-21', alerta_minimo:1, emoji:'🍕', descricao:'Molho artesanal, mussarela fresca, manjericão' },
    { id:5, nome:'Pizza Calabresa', categoria:'pizzas', quantidade:0, valor_unitario:58.00, prazo_validade:'2026-03-21', alerta_minimo:1, emoji:'🍕', descricao:'Calabresa artesanal, cebola roxa, azeitona' },
    { id:6, nome:'Água Mineral 500ml', categoria:'bebidas', quantidade:24, valor_unitario:3.50, prazo_validade:'2027-06-01', alerta_minimo:12, emoji:'💧', descricao:'Água mineral natural' },
    { id:7, nome:'Suco Natural Laranja', categoria:'bebidas', quantidade:6, valor_unitario:8.00, prazo_validade:'2026-03-15', alerta_minimo:4, emoji:'🍊', descricao:'Suco 100% natural, sem adição de açúcar' },
  ],
  insumos: [
    { id:1, nome:'Farinha Especial T65', categoria:'farinhas', quantidade:10, unidade:'kg', valor_unitario:8.50, prazo_validade:'2026-09-01', alerta_minimo:5 },
    { id:2, nome:'Farinha de Arroz', categoria:'farinhas', quantidade:3, unidade:'kg', valor_unitario:6.00, prazo_validade:'2026-08-01', alerta_minimo:2 },
    { id:3, nome:'Polvilho Doce', categoria:'farinhas', quantidade:2, unidade:'kg', valor_unitario:7.00, prazo_validade:'2026-07-01', alerta_minimo:2 },
    { id:4, nome:'Água Mineral (galão 20L)', categoria:'agua_mineral', quantidade:2, unidade:'unid', valor_unitario:12.00, prazo_validade:'2027-01-01', alerta_minimo:2 },
    { id:5, nome:'Fermento Biológico Fresco', categoria:'fermento_biologico', quantidade:0.5, unidade:'kg', valor_unitario:15.00, prazo_validade:'2026-03-20', alerta_minimo:0.3 },
    { id:6, nome:'Azeite Extra Virgem', categoria:'condimentos', quantidade:2, unidade:'L', valor_unitario:35.00, prazo_validade:'2027-03-01', alerta_minimo:1 },
    { id:7, nome:'Sal Rosa Himalaia', categoria:'condimentos', quantidade:0.8, unidade:'kg', valor_unitario:12.00, prazo_validade:'2028-01-01', alerta_minimo:0.5 },
    { id:8, nome:'Ovos Caipira', categoria:'produtos_alimentares', quantidade:12, unidade:'unid', valor_unitario:1.20, prazo_validade:'2026-03-25', alerta_minimo:6 },
    { id:9, nome:'Botijão de Gás 13kg', categoria:'gas', quantidade:1, unidade:'unid', valor_unitario:140.00, prazo_validade:null, alerta_minimo:1 },
    { id:10, nome:'Caixas de Papelão (Kit 10)', categoria:'embalagens', quantidade:20, unidade:'unid', valor_unitario:2.00, prazo_validade:null, alerta_minimo:10 },
    { id:11, nome:'Sacolas Kraft', categoria:'embalagens', quantidade:50, unidade:'unid', valor_unitario:0.80, prazo_validade:null, alerta_minimo:20 },
    { id:12, nome:'Detergente Neutro', categoria:'produtos_limpeza', quantidade:3, unidade:'unid', valor_unitario:4.50, prazo_validade:'2028-01-01', alerta_minimo:2 },
  ],
  fichas: [
    { id:1, produto_id:1, valor_venda_unitario:18.00, custo_material:3.20, custo_mao_obra:2.00, custo_bruto_producao:5.20, margem_lucro:71.1, modo_preparo:'Misturar farinha T65, água filtrada (68% hidratação), fermento biológico (0,2%) e sal (2%). Autólise 30min. Dobras a cada 30min por 2h. Formatar os pães e refrigerar 18-24h (fermentação retardada). Pré-aquecer forno com pedra a 240°C. Assar com vapor por 10min, depois abrir forno e completar 15min até casca dourada.', peso_cru:400, peso_pronto:340, percentual_perda:15 },
    { id:2, produto_id:2, valor_venda_unitario:18.00, custo_material:3.80, custo_mao_obra:2.00, custo_bruto_producao:5.80, margem_lucro:67.8, modo_preparo:'Misturar polvilho doce, ovos caipira, azeite, água morna e sal. Fermentação 12h. Modelar e assar a 200°C por 30min.', peso_cru:380, peso_pronto:310, percentual_perda:18.4 },
    { id:3, produto_id:3, valor_venda_unitario:32.00, custo_material:6.50, custo_mao_obra:3.00, custo_bruto_producao:9.50, margem_lucro:70.3, modo_preparo:'Massa de brioche enriquecida com ovos caipira (3 unid/kg farinha). Fermentação longa 24h refrigerada. Trançar em 3 ou 4 filetes. Assar a 180°C por 35min com ovo para lustrar.', peso_cru:600, peso_pronto:500, percentual_perda:16.7 },
    { id:4, produto_id:4, valor_venda_unitario:55.00, custo_material:12.00, custo_mao_obra:5.00, custo_bruto_producao:17.00, margem_lucro:69.1, modo_preparo:'Massa de pizza de longa fermentação (48h). Molho artesanal de tomate pelado. Cobrir com mussarela frescal fatiada. Decorar com folhas de manjericão fresco. Assar em forno a 300°C por 12-15min.', peso_cru:500, peso_pronto:420, percentual_perda:16 },
  ],
  producoes: [
    { id:1, data:'2026-03-12', produto_id:1, quantidade:20, operador:'Tiberio Gadelha', observacao:'Fornada quarta-feira - todos vendidos', pago_colaborador:false },
    { id:2, data:'2026-03-12', produto_id:2, quantidade:10, operador:'Tiberio Gadelha', observacao:'Fornada quarta-feira', pago_colaborador:false },
    { id:3, data:'2026-03-12', produto_id:3, quantidade:8, operador:'Tiberio Gadelha', observacao:'Fornada quarta-feira', pago_colaborador:false },
    { id:4, data:'2026-03-07', produto_id:4, quantidade:6, operador:'Tiberio Gadelha', observacao:'Fornada sexta-feira - pizzas', pago_colaborador:false },
    { id:5, data:'2026-03-07', produto_id:1, quantidade:15, operador:'Tiberio Gadelha', observacao:'Fornada sexta-feira', pago_colaborador:false },
    { id:6, data:'2026-03-07', produto_id:5, quantidade:4, operador:'Tiberio Gadelha', observacao:'Fornada sexta-feira - pizzas', pago_colaborador:false },
    { id:7, data:'2026-02-26', produto_id:1, quantidade:18, operador:'Tiberio Gadelha', observacao:'Fornada quarta-feira', pago_colaborador:false },
    { id:8, data:'2026-02-26', produto_id:3, quantidade:6, operador:'Tiberio Gadelha', observacao:'Fornada quarta-feira', pago_colaborador:false },
  ],
  clientes: [
    { id:1, nome:'Selva / Jovanka', whatsapp:'55 (73) 99999-1111', instagram:'@selva.jovanka', endereco_completo:'Rua das Flores, 123, Bairro Novo, Ilhéus-BA', localidade_id:1, link_googlemaps:'https://maps.google.com', foto_fachada_url:null, preferencias:'Bambuguette, sem sal extra', data_cadastro:'2026-01-15', grupo_id:3 },
    { id:2, nome:'Maria das Graças', whatsapp:'55 (73) 99999-2222', instagram:'@mariadasgracas', endereco_completo:'Av. Principal, 456, Centro, Ilhéus-BA', localidade_id:1, link_googlemaps:'https://maps.google.com', foto_fachada_url:null, preferencias:'Pão Trançado, pizza margherita', data_cadastro:'2026-01-20', grupo_id:4 },
    { id:3, nome:'João Pedro Silva', whatsapp:'55 (73) 99999-3333', instagram:'@joaopsilva', endereco_completo:'Rua do Mar, 789, Barra, Ilhéus-BA', localidade_id:2, link_googlemaps:'https://maps.google.com', foto_fachada_url:null, preferencias:'Bambuguette Sem Glúten', data_cadastro:'2026-02-10', grupo_id:2 },
    { id:4, nome:'Ana Luiza Ferreira', whatsapp:'55 (73) 99999-4444', instagram:'@analuizaf', endereco_completo:'Travessa das Palmeiras, 321, São Domingos, Ilhéus-BA', localidade_id:3, link_googlemaps:null, foto_fachada_url:null, preferencias:'Pizza Calabresa', data_cadastro:'2026-03-12', grupo_id:1 },
    { id:5, nome:'Carlos Mendes', whatsapp:'55 (73) 99999-5555', instagram:null, endereco_completo:'Rua Nova, 654, Centro, Ilhéus-BA', localidade_id:1, link_googlemaps:'https://maps.google.com', foto_fachada_url:null, preferencias:'Pão Trançado', data_cadastro:'2025-12-20', grupo_id:4 },
    { id:6, nome:'Beatriz Lima', whatsapp:'55 (73) 99999-6666', instagram:'@bia.lima', endereco_completo:'Rua das Mangueiras, 900, Conquista, Ilhéus-BA', localidade_id:3, link_googlemaps:null, foto_fachada_url:null, preferencias:'Bambuguette', data_cadastro:'2026-02-28', grupo_id:2 },
  ],
  grupos: [
    { id:1, nome_grupo:'potenciais clientes', descricao:'Contatos que ainda não fizeram pedido', cor:'#6B7280', lista_cliente_ids:[4] },
    { id:2, nome_grupo:'clientes novos', descricao:'Realizaram 1 pedido', cor:C.blue, lista_cliente_ids:[3,6] },
    { id:3, nome_grupo:'clientes esporádicos', descricao:'2-3 pedidos no total', cor:C.yellow, lista_cliente_ids:[1] },
    { id:4, nome_grupo:'clientes fixos', descricao:'4+ pedidos por mês', cor:C.green, lista_cliente_ids:[2,5] },
    { id:5, nome_grupo:'colaborador', descricao:'Parceiros e equipe', cor:C.purple, lista_cliente_ids:[] },
  ],
  localidades: [
    { id:1, nome_localidade:'Centro / Bairro Novo', rota_descricao:'Região central de Ilhéus', valor_entrega:8.00, link_rota_maps:'https://maps.google.com' },
    { id:2, nome_localidade:'Barra / Praia do Sul', rota_descricao:'Orla sul da cidade', valor_entrega:12.00, link_rota_maps:'https://maps.google.com' },
    { id:3, nome_localidade:'São Domingos / Conquista', rota_descricao:'Região norte de Ilhéus', valor_entrega:10.00, link_rota_maps:'https://maps.google.com' },
    { id:4, nome_localidade:'Retirada no Ponto', rota_descricao:'Cliente retira — sem custo de entrega', valor_entrega:0.00, link_rota_maps:null },
  ],
  mensagens: [
    { id:1, cliente_id:1, canal:'whatsapp', data_hora:'2026-03-14T08:30', conteudo:'Oi! Quero encomendar 2 Bambuguettes para quarta. Pode ser?', status:'lida', pedido_id:null, de_cliente:true },
    { id:2, cliente_id:1, canal:'whatsapp', data_hora:'2026-03-14T08:35', conteudo:'Oi Selva! Claro, temos disponibilidade. 2 Bambuguettes confirmados para quarta (18/03), entrega das 7h30–9h. Total: R$36,00 + frete R$8,00 = R$44,00. Pagamento via PIX: 73999991111. ✅', status:'lida', pedido_id:4, de_cliente:false },
    { id:3, cliente_id:1, canal:'whatsapp', data_hora:'2026-03-14T08:40', conteudo:'Perfeito! Vou fazer o PIX agora.', status:'lida', pedido_id:null, de_cliente:true },
    { id:4, cliente_id:2, canal:'instagram', data_hora:'2026-03-13T15:00', conteudo:'Boa tarde! Tem pizza disponível para sexta-feira?', status:'nao_lida', pedido_id:null, de_cliente:true },
    { id:5, cliente_id:3, canal:'whatsapp', data_hora:'2026-03-13T10:00', conteudo:'Olá, quero um Pão Trançado para sexta-feira. Como faço?', status:'nao_lida', pedido_id:null, de_cliente:true },
    { id:6, cliente_id:6, canal:'instagram', data_hora:'2026-03-12T18:00', conteudo:'Amei o pão da última vez! Quero pedir de novo 🥖', status:'lida', pedido_id:null, de_cliente:true },
  ],
  pedidos: [
    { id:1, cliente_id:2, localidade_id:1, data_pedido:'2026-03-01T09:00', data_entrega:'2026-03-07T08:00', itens:[{produto_id:1, quantidade:2, valor:36.00},{produto_id:3, quantidade:1, valor:32.00}], valor_total:68.00, status_producao:'pronto', status_entrega:'entregue', pagamento_confirmado:true, observacoes:'' },
    { id:2, cliente_id:5, localidade_id:4, data_pedido:'2026-03-02T10:00', data_entrega:'2026-03-07T08:00', itens:[{produto_id:3, quantidade:1, valor:32.00}], valor_total:32.00, status_producao:'pronto', status_entrega:'entregue', pagamento_confirmado:true, observacoes:'Retirada no ponto' },
    { id:3, cliente_id:1, localidade_id:1, data_pedido:'2026-03-09T01:53', data_entrega:'2026-03-12T08:00', itens:[{produto_id:1, quantidade:2, valor:36.00},{produto_id:2, quantidade:1, valor:18.00}], valor_total:62.00, status_producao:'pronto', status_entrega:'entregue', pagamento_confirmado:true, observacoes:'' },
    { id:4, cliente_id:1, localidade_id:1, data_pedido:'2026-03-14T08:30', data_entrega:'2026-03-18T08:00', itens:[{produto_id:1, quantidade:2, valor:36.00}], valor_total:44.00, status_producao:'pendente', status_entrega:'aguardando', pagamento_confirmado:false, observacoes:'Aguardando confirmação pagamento' },
    { id:5, cliente_id:3, localidade_id:4, data_pedido:'2026-03-14T10:00', data_entrega:'2026-03-18T08:00', itens:[{produto_id:3, quantidade:1, valor:32.00}], valor_total:32.00, status_producao:'pendente', status_entrega:'aguardando', pagamento_confirmado:false, observacoes:'' },
    { id:6, cliente_id:6, localidade_id:3, data_pedido:'2026-03-13T19:00', data_entrega:'2026-03-21T17:00', itens:[{produto_id:1, quantidade:1, valor:18.00},{produto_id:4, quantidade:1, valor:55.00}], valor_total:83.00, status_producao:'pendente', status_entrega:'aguardando', pagamento_confirmado:false, observacoes:'Sexta-feira noite' },
  ],
  rotas: [
    { id:1, nome_rota:'Rota Centro — Quarta 18/03', data:'2026-03-18', lista_pedido_ids:[4,5], status_rota:'planejado', entregador:'Tiberio' },
    { id:2, nome_rota:'Rota Norte — Sexta 21/03', data:'2026-03-21', lista_pedido_ids:[6], status_rota:'planejado', entregador:'Tiberio' },
  ],
  colaboradores: [
    { id:1, nome:'Tiberio Gadelha', funcao:'Produtor / Gestor', whatsapp:'55 (73) 99999-0000', valor_por_fornada:null, ativo:true },
  ],
  bens: [
    { id:1, nome:'Forno Elétrico Industrial', valor:2800.00, data_aquisicao:'2025-06-01', categoria:'Equipamentos', depreciado:false },
    { id:2, nome:'Batedeira Planetária 7L', valor:850.00, data_aquisicao:'2025-08-15', categoria:'Equipamentos', depreciado:false },
    { id:3, nome:'Pedra de Assar', valor:180.00, data_aquisicao:'2025-06-01', categoria:'Utensílios', depreciado:false },
  ],
  settings: {
    meta_faturamento:3000.00, nome_empresa:'Taboca Pão e Pizza', responsavel:'Tiberio Gadelha', cargo:'DIRETOR DE OPERAÇÕES',
    prompt_agente1:`Você é o assistente de gestão pessoal de Tiba, proprietário da Taboca Pão e Pizza.\nSeu papel é ajudá-lo a gerenciar o negócio com agilidade e precisão.\nVocê tem acesso aos dados do sistema e pode ler, inserir e editar registros.\nResponda de forma direta e objetiva com linguagem informal amigável.\nAo apresentar relatórios, use formato estruturado com números em destaque.\nLembre das preferências de Tiba para antecipar suas necessidades.`,
    prompt_agente2:`Você é o atendente virtual da Taboca Pão e Pizza.\nAtenda com simpatia, agilidade e personalização.\n1. Cumprimente pelo nome se o cliente já estiver cadastrado.\n2. Seja breve — ninguém gosta de textos longos no WhatsApp.\n3. Apresente o cardápio por categoria quando solicitado.\n4. Registre pedidos confirmando cada item antes de finalizar.\n5. Informe data/horário de entrega e valor do frete por localidade.\n6. Solicite confirmação de pagamento e método (PIX, dinheiro, cartão).\n7. Encerre agradecendo e informando o status do pedido.`,
    contas: [
      { id:1, nome:'Caixa em Dinheiro', saldo_inicial:200.00 },
      { id:2, nome:'PIX / Conta Digital', saldo_inicial:50000.00 },
      { id:3, nome:'Conta Corrente Caixa', saldo_inicial:0 },
    ],
    capital_social: 50000.00,
  },
  fornadas: [
    { id:1, data:'2026-03-18', hora_inicio:'07:30', hora_fim:'09:00', tipo:'Pães', encerramento_encomenda:'2026-03-16T21:00' },
    { id:2, data:'2026-03-21', hora_inicio:'17:00', hora_fim:'21:00', tipo:'Pães + Pizzas', encerramento_encomenda:'2026-03-19T09:00' },
  ],
  activityLog: [
    { id:1, tipo:'transacao', descricao:'Botijão de gás — R$ 140,00', data:'2026-03-23T12:00', operador:'Tiberio', icon:'despesa' },
    { id:2, tipo:'transacao', descricao:'Compra pacote IA — R$ 96,99', data:'2026-03-20T12:00', operador:'Tiberio', icon:'despesa' },
    { id:3, tipo:'transacao', descricao:'Venda Pedido #3 — R$ 54,00', data:'2026-03-09T01:53', operador:'TABOCA', icon:'receita' },
    { id:4, tipo:'pedido', descricao:'Novo Pedido #3 — Selva/Jovanka — R$ 54,00', data:'2026-03-09T01:53', operador:'TABOCA', icon:'pedido' },
  ],
  campanhas: [],
  whatsapp_config: { id:1, provider:'official', api_url:'https://graph.facebook.com/v18.0', api_token:'', phone_number:'', phone_number_id:'', webhook_secret:'', auto_reply:false },
  instagram_config: { id:1, page_id:'', access_token:'', ig_user_id:'', webhook_verify_token:'', auto_reply:false },
});
